get:
  description: Returns all accessible config of the app
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '../schemas/Configuration.yaml'
  tags:
    - Configuration
