get:
  description: 'Returns all accessible config of the app'
  tags:
    - Configuration
  responses:
    '200':
      description: 'Successful response'
      content:
        application/json:
          schema:
            $ref: '../schemas/Configuration.yaml'
