x-swagger-router-controller: mock
get:
  description: |
    Request all available Product Tests
  parameters:
    - name: filter
      in: query
      description: Filter product tests
      required: false
      schema:
        type: string
        default: all
        enum:
          - all
          - completed
          - actual
          - teaser
    - $ref: '../parameters/Page.yaml'
    - allOf:
      - $ref: '../parameters/PerPage.yaml'
      - description: Items per page, can be 5 to 50 (inclusive)
        schema:
            default: 20
            minimum: 5
            maximum: 50
    - $ref: '../parameters/Schema.yaml'
    - $ref: '../parameters/X-User-Token-Optional.yaml'
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '../schemas/ProducttestsResponse.yaml'
  tags:
    - ProductTest
