x-swagger-router-controller: mock
get:
  description: |
    Request details of the product test.
    Depending on the phase different fields can be returned.
  parameters:
    - name: uuid
      in: path
      required: true
      schema:
        type: string
        format: bl-uuid
    - $ref: '../parameters/Schema.yaml'
    - $ref: '../parameters/X-User-Token-Optional.yaml'
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '../schemas/ProducttestsResponse.yaml'
  tags:
    - ProductTest
