x-swagger-router-controller: mock
get:
  description: |
    Request details of the product test.
    Depending on the phase different fields can be returned.
  parameters:
    - name: uuid
      required: true
      in: path
      schema:
        type: string
    - $ref: '../parameters/Schema.yaml'
  tags:
    - ProductTest
  responses:
    '200':
      description: Succssful response
      content:
        application/json:
          schema:
            $ref: '../schemas/ProducttestsResponse.yaml'
