x-swagger-router-controller: mock
get:
  description: |
    Request all available Product Tests
  tags:
    - ProductTest
  parameters:
    - $ref: '../parameters/Schema.yaml'
  responses:
    '200':
      description: Succssful response
      content:
        application/json:
          schema:
            $ref: '../schemas/ProducttestsResponse.yaml'
