x-swagger-router-controller: mock
get:
  description: |
    Request all available Product Tests
  produces:
    - application/json
  tags:
    - ProductTest
  parameters:
    - $ref: '../parameters/Schema.yaml'
  responses:
    '200':
      description: Succssful response
      schema:
        $ref: '../schemas/ProducttestsResponse.yaml'
