type: object
required:
  - list
properties:
  list:
    type: array
    items:
      type: object
      required:
        - id
        - name
        - values
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
        "values":
          type: object
          required:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
          properties:
            "1":
              type: integer
              minimum: 0
            "2":
              type: integer
              minimum: 0
            "3":
              type: integer
              minimum: 0
            "4":
              type: integer
              minimum: 0
            "5":
              type: integer
              minimum: 0
        average:
          type: number
          minimum: 0
          maximum: 5
